#!/bin/bash

authors()
{
    echo "Authors"
}

clone()
{
    echo "Clone"
}

migrate()
{
    echo "Migrate"
}

usage()
{
    echo "usage: options [[-A ] [-c] [-m] [-h]]"
}

while getopts "Acmh:" option; do
    case "$option" in
        -A | --authors) authors
                        exit 0
                        ;;
        -c | --clonw)   clone
                        exit 0
                        ;;
        -m | --migrate) migrate
                        exit 0
                        ;;
        -h | --help)    usage
                        exit 0
                        ;;
        ?)              echo "usage"
                        usage
                        exit 1
    esac
done
